//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIV.CentralCenterClient.CentralCenterServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportBO", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    [System.SerializableAttribute()]
    public partial class ReportBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostField;
        
        private System.Guid OwnerField;
        
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CivVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogElementBOSerializedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Host {
            get {
                return this.HostField;
            }
            set {
                if ((object.ReferenceEquals(this.HostField, value) != true)) {
                    this.HostField = value;
                    this.RaisePropertyChanged("Host");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Guid Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((this.OwnerField.Equals(value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CivVersion {
            get {
                return this.CivVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.CivVersionField, value) != true)) {
                    this.CivVersionField = value;
                    this.RaisePropertyChanged("CivVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LogElementBOSerialized {
            get {
                return this.LogElementBOSerializedField;
            }
            set {
                if ((object.ReferenceEquals(this.LogElementBOSerializedField, value) != true)) {
                    this.LogElementBOSerializedField = value;
                    this.RaisePropertyChanged("LogElementBOSerialized");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternetAccessBO", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    [System.SerializableAttribute()]
    public partial class InternetAccessBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameFrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameEnField;
        
        private double TotalCombinedField;
        
        private double OverChargeField;
        
        private int MaxCostField;
        
        private double UploadSpeedField;
        
        private double DownloadSpeedField;
        
        private System.DateTime LastUpdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameFr {
            get {
                return this.NameFrField;
            }
            set {
                if ((object.ReferenceEquals(this.NameFrField, value) != true)) {
                    this.NameFrField = value;
                    this.RaisePropertyChanged("NameFr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NameEn {
            get {
                return this.NameEnField;
            }
            set {
                if ((object.ReferenceEquals(this.NameEnField, value) != true)) {
                    this.NameEnField = value;
                    this.RaisePropertyChanged("NameEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double TotalCombined {
            get {
                return this.TotalCombinedField;
            }
            set {
                if ((this.TotalCombinedField.Equals(value) != true)) {
                    this.TotalCombinedField = value;
                    this.RaisePropertyChanged("TotalCombined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double OverCharge {
            get {
                return this.OverChargeField;
            }
            set {
                if ((this.OverChargeField.Equals(value) != true)) {
                    this.OverChargeField = value;
                    this.RaisePropertyChanged("OverCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int MaxCost {
            get {
                return this.MaxCostField;
            }
            set {
                if ((this.MaxCostField.Equals(value) != true)) {
                    this.MaxCostField = value;
                    this.RaisePropertyChanged("MaxCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double UploadSpeed {
            get {
                return this.UploadSpeedField;
            }
            set {
                if ((this.UploadSpeedField.Equals(value) != true)) {
                    this.UploadSpeedField = value;
                    this.RaisePropertyChanged("UploadSpeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double DownloadSpeed {
            get {
                return this.DownloadSpeedField;
            }
            set {
                if ((this.DownloadSpeedField.Equals(value) != true)) {
                    this.DownloadSpeedField = value;
                    this.RaisePropertyChanged("DownloadSpeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime LastUpdate {
            get {
                return this.LastUpdateField;
            }
            set {
                if ((this.LastUpdateField.Equals(value) != true)) {
                    this.LastUpdateField = value;
                    this.RaisePropertyChanged("LastUpdate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReleaseBO", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    [System.SerializableAttribute()]
    public partial class ReleaseBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        private System.DateTime ReleaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        private int SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Release {
            get {
                return this.ReleaseField;
            }
            set {
                if ((this.ReleaseField.Equals(value) != true)) {
                    this.ReleaseField = value;
                    this.RaisePropertyChanged("Release");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string History {
            get {
                return this.HistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoryField, value) != true)) {
                    this.HistoryField = value;
                    this.RaisePropertyChanged("History");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CRC {
            get {
                return this.CRCField;
            }
            set {
                if ((object.ReferenceEquals(this.CRCField, value) != true)) {
                    this.CRCField = value;
                    this.RaisePropertyChanged("CRC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", ConfigurationName="CentralCenterServiceReference.CentralCenterSoap")]
    public interface CentralCenterSoap {
        
        // CODEGEN: Generating message contract since element name version from namespace http://CodexMundus.net/CentralCenter_v3_6_0/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CodexMundus.net/CentralCenter_v3_6_0/IsCompatibleClient", ReplyAction="*")]
        CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientResponse IsCompatibleClient(CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientRequest request);
        
        // CODEGEN: Generating message contract since element name element from namespace http://CodexMundus.net/CentralCenter_v3_6_0/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CodexMundus.net/CentralCenter_v3_6_0/SendReport", ReplyAction="*")]
        CIV.CentralCenterClient.CentralCenterServiceReference.SendReportResponse SendReport(CIV.CentralCenterClient.CentralCenterServiceReference.SendReportRequest request);
        
        // CODEGEN: Generating message contract since element name GetInternetAccessResult from namespace http://CodexMundus.net/CentralCenter_v3_6_0/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CodexMundus.net/CentralCenter_v3_6_0/GetInternetAccess", ReplyAction="*")]
        CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessResponse GetInternetAccess(CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://CodexMundus.net/CentralCenter_v3_6_0/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CodexMundus.net/CentralCenter_v3_6_0/IsLastVersion", ReplyAction="*")]
        CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionResponse IsLastVersion(CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://CodexMundus.net/CentralCenter_v3_6_0/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CodexMundus.net/CentralCenter_v3_6_0/GetLastVersion", ReplyAction="*")]
        CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionResponse GetLastVersion(CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionRequest request);
        
        // CODEGEN: Generating message contract since element name RunningVersionResult from namespace http://CodexMundus.net/CentralCenter_v3_6_0/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CodexMundus.net/CentralCenter_v3_6_0/RunningVersion", ReplyAction="*")]
        CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionResponse RunningVersion(CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionRequest request);
        
        // CODEGEN: Generating message contract since element name version from namespace http://CodexMundus.net/CentralCenter_v3_6_0/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CodexMundus.net/CentralCenter_v3_6_0/NewInstallation", ReplyAction="*")]
        CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationResponse NewInstallation(CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsCompatibleClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsCompatibleClient", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientRequestBody Body;
        
        public IsCompatibleClientRequest() {
        }
        
        public IsCompatibleClientRequest(CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    public partial class IsCompatibleClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string version;
        
        public IsCompatibleClientRequestBody() {
        }
        
        public IsCompatibleClientRequestBody(string version) {
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsCompatibleClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsCompatibleClientResponse", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientResponseBody Body;
        
        public IsCompatibleClientResponse() {
        }
        
        public IsCompatibleClientResponse(CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    public partial class IsCompatibleClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsCompatibleClientResult;
        
        public IsCompatibleClientResponseBody() {
        }
        
        public IsCompatibleClientResponseBody(bool IsCompatibleClientResult) {
            this.IsCompatibleClientResult = IsCompatibleClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendReport", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.SendReportRequestBody Body;
        
        public SendReportRequest() {
        }
        
        public SendReportRequest(CIV.CentralCenterClient.CentralCenterServiceReference.SendReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    public partial class SendReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.ReportBO element;
        
        public SendReportRequestBody() {
        }
        
        public SendReportRequestBody(CIV.CentralCenterClient.CentralCenterServiceReference.ReportBO element) {
            this.element = element;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendReportResponse", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.SendReportResponseBody Body;
        
        public SendReportResponse() {
        }
        
        public SendReportResponse(CIV.CentralCenterClient.CentralCenterServiceReference.SendReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendReportResponseBody {
        
        public SendReportResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInternetAccessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInternetAccess", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessRequestBody Body;
        
        public GetInternetAccessRequest() {
        }
        
        public GetInternetAccessRequest(CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInternetAccessRequestBody {
        
        public GetInternetAccessRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInternetAccessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInternetAccessResponse", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessResponseBody Body;
        
        public GetInternetAccessResponse() {
        }
        
        public GetInternetAccessResponse(CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    public partial class GetInternetAccessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.InternetAccessBO[] GetInternetAccessResult;
        
        public GetInternetAccessResponseBody() {
        }
        
        public GetInternetAccessResponseBody(CIV.CentralCenterClient.CentralCenterServiceReference.InternetAccessBO[] GetInternetAccessResult) {
            this.GetInternetAccessResult = GetInternetAccessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLastVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLastVersion", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionRequestBody Body;
        
        public IsLastVersionRequest() {
        }
        
        public IsLastVersionRequest(CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    public partial class IsLastVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string number;
        
        public IsLastVersionRequestBody() {
        }
        
        public IsLastVersionRequestBody(string category, string number) {
            this.category = category;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsLastVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsLastVersionResponse", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionResponseBody Body;
        
        public IsLastVersionResponse() {
        }
        
        public IsLastVersionResponse(CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    public partial class IsLastVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsLastVersionResult;
        
        public IsLastVersionResponseBody() {
        }
        
        public IsLastVersionResponseBody(bool IsLastVersionResult) {
            this.IsLastVersionResult = IsLastVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastVersion", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionRequestBody Body;
        
        public GetLastVersionRequest() {
        }
        
        public GetLastVersionRequest(CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    public partial class GetLastVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        public GetLastVersionRequestBody() {
        }
        
        public GetLastVersionRequestBody(string category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastVersionResponse", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionResponseBody Body;
        
        public GetLastVersionResponse() {
        }
        
        public GetLastVersionResponse(CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    public partial class GetLastVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.ReleaseBO GetLastVersionResult;
        
        public GetLastVersionResponseBody() {
        }
        
        public GetLastVersionResponseBody(CIV.CentralCenterClient.CentralCenterServiceReference.ReleaseBO GetLastVersionResult) {
            this.GetLastVersionResult = GetLastVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunningVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunningVersion", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionRequestBody Body;
        
        public RunningVersionRequest() {
        }
        
        public RunningVersionRequest(CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RunningVersionRequestBody {
        
        public RunningVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunningVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunningVersionResponse", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionResponseBody Body;
        
        public RunningVersionResponse() {
        }
        
        public RunningVersionResponse(CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    public partial class RunningVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RunningVersionResult;
        
        public RunningVersionResponseBody() {
        }
        
        public RunningVersionResponseBody(string RunningVersionResult) {
            this.RunningVersionResult = RunningVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewInstallationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewInstallation", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationRequestBody Body;
        
        public NewInstallationRequest() {
        }
        
        public NewInstallationRequest(CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/")]
    public partial class NewInstallationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid owner;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string version;
        
        public NewInstallationRequestBody() {
        }
        
        public NewInstallationRequestBody(System.Guid owner, string version) {
            this.owner = owner;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewInstallationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewInstallationResponse", Namespace="http://CodexMundus.net/CentralCenter_v3_6_0/", Order=0)]
        public CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationResponseBody Body;
        
        public NewInstallationResponse() {
        }
        
        public NewInstallationResponse(CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NewInstallationResponseBody {
        
        public NewInstallationResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CentralCenterSoapChannel : CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentralCenterSoapClient : System.ServiceModel.ClientBase<CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap>, CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap {
        
        public CentralCenterSoapClient() {
        }
        
        public CentralCenterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CentralCenterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentralCenterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentralCenterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientResponse CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap.IsCompatibleClient(CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientRequest request) {
            return base.Channel.IsCompatibleClient(request);
        }
        
        public bool IsCompatibleClient(string version) {
            CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientRequest inValue = new CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientRequest();
            inValue.Body = new CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientRequestBody();
            inValue.Body.version = version;
            CIV.CentralCenterClient.CentralCenterServiceReference.IsCompatibleClientResponse retVal = ((CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap)(this)).IsCompatibleClient(inValue);
            return retVal.Body.IsCompatibleClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIV.CentralCenterClient.CentralCenterServiceReference.SendReportResponse CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap.SendReport(CIV.CentralCenterClient.CentralCenterServiceReference.SendReportRequest request) {
            return base.Channel.SendReport(request);
        }
        
        public void SendReport(CIV.CentralCenterClient.CentralCenterServiceReference.ReportBO element) {
            CIV.CentralCenterClient.CentralCenterServiceReference.SendReportRequest inValue = new CIV.CentralCenterClient.CentralCenterServiceReference.SendReportRequest();
            inValue.Body = new CIV.CentralCenterClient.CentralCenterServiceReference.SendReportRequestBody();
            inValue.Body.element = element;
            CIV.CentralCenterClient.CentralCenterServiceReference.SendReportResponse retVal = ((CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap)(this)).SendReport(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessResponse CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap.GetInternetAccess(CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessRequest request) {
            return base.Channel.GetInternetAccess(request);
        }
        
        public CIV.CentralCenterClient.CentralCenterServiceReference.InternetAccessBO[] GetInternetAccess() {
            CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessRequest inValue = new CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessRequest();
            inValue.Body = new CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessRequestBody();
            CIV.CentralCenterClient.CentralCenterServiceReference.GetInternetAccessResponse retVal = ((CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap)(this)).GetInternetAccess(inValue);
            return retVal.Body.GetInternetAccessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionResponse CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap.IsLastVersion(CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionRequest request) {
            return base.Channel.IsLastVersion(request);
        }
        
        public bool IsLastVersion(string category, string number) {
            CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionRequest inValue = new CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionRequest();
            inValue.Body = new CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionRequestBody();
            inValue.Body.category = category;
            inValue.Body.number = number;
            CIV.CentralCenterClient.CentralCenterServiceReference.IsLastVersionResponse retVal = ((CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap)(this)).IsLastVersion(inValue);
            return retVal.Body.IsLastVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionResponse CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap.GetLastVersion(CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionRequest request) {
            return base.Channel.GetLastVersion(request);
        }
        
        public CIV.CentralCenterClient.CentralCenterServiceReference.ReleaseBO GetLastVersion(string category) {
            CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionRequest inValue = new CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionRequest();
            inValue.Body = new CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionRequestBody();
            inValue.Body.category = category;
            CIV.CentralCenterClient.CentralCenterServiceReference.GetLastVersionResponse retVal = ((CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap)(this)).GetLastVersion(inValue);
            return retVal.Body.GetLastVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionResponse CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap.RunningVersion(CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionRequest request) {
            return base.Channel.RunningVersion(request);
        }
        
        public string RunningVersion() {
            CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionRequest inValue = new CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionRequest();
            inValue.Body = new CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionRequestBody();
            CIV.CentralCenterClient.CentralCenterServiceReference.RunningVersionResponse retVal = ((CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap)(this)).RunningVersion(inValue);
            return retVal.Body.RunningVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationResponse CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap.NewInstallation(CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationRequest request) {
            return base.Channel.NewInstallation(request);
        }
        
        public void NewInstallation(System.Guid owner, string version) {
            CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationRequest inValue = new CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationRequest();
            inValue.Body = new CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationRequestBody();
            inValue.Body.owner = owner;
            inValue.Body.version = version;
            CIV.CentralCenterClient.CentralCenterServiceReference.NewInstallationResponse retVal = ((CIV.CentralCenterClient.CentralCenterServiceReference.CentralCenterSoap)(this)).NewInstallation(inValue);
        }
    }
}
